package main

import (
	"encoding/json"
	"hello/entities"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// Hanya terima GET
		if r.Method != http.MethodGet {
			http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
			return
		}

		// Contoh data AutoGenerated
		data := entities.Hehe{
			Model: "contoh-model",
			Messages: []entities.Message{
				{
					Role:    "user",
					Content: "hello world",
				},
				{
					Role:    "system",
					Content: "response from system 1",
				},
			},
			Stream: true,
		}

		// Set header untuk streaming
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Transfer-Encoding", "chunked")

		// Buat encoder untuk streaming
		encoder := json.NewEncoder(w)

		// Stream data ke klien
		if err := encoder.Encode(data); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	})

	// Menjalankan server di port 8080
	log.Println("Server berjalan di http://localhost:9090")
	log.Fatal(http.ListenAndServe(":9090", nil))
}
