name: Secure Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Minimal permission untuk upload asset

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Untuk mendapatkan tag lengkap

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Build
        run: |
          go mod download
          go build -o hello-github
          sha256sum hello-github > checksum.txt

      - name: Create Release Asset
        run: |
          tar -czvf hello-github.tar.gz hello-github
          sha256sum hello-github.tar.gz >> checksum.txt

      - name: Upload Release Asset
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: hello-github.tar.gz
          tags: true
          draft: false

      - name: Upload Checksum
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: checksum.txt
          tags: true
          draft: false
